const express = require('express');
const router = express.Router();

// Generated by Copilot
// All web routes register here //

// Health check endpoint
router.get('/health', (req, res) => {
  res.json({
    success: true,
    message: 'Web API is running',
    timestamp: new Date().toISOString(),
    environment: process.env.NODE_ENV
  });
});

// Basic routes - will be replaced with actual modules
router.get('/', (req, res) => {
  res.json({
    success: true,
    message: 'Project Management Web API',
    version: '1.0.0',
    endpoints: {
      health: '/api/web/health',
      auth: '/api/web/auth (coming soon)',
      dashboard: '/api/web/dashboard (coming soon)',
      reports: '/api/web/reports (coming soon)',
      analytics: '/api/web/analytics (coming soon)'
    }
  });
});

// TODO: Add actual module routes when they are created
// const authRoutes = require('../modules/auth/auth.routes');
// router.use('/auth', authRoutes);

// const dashboardRoutes = require('../modules/dashboard/dashboard.routes');
// router.use('/dashboard', dashboardRoutes);

module.exports = router;
