const express = require('express');
const router = express.Router();
const authController = require('./auth.controller');
const authValidator = require('./auth.validator');

class AuthRoutes {
    constructor() {
        this.router = express.Router();
        this.initializeRoutes();
    }

    initializeRoutes() {
        // Registration route
        this.router.post('/register', 
            authValidator.registerValidation,
            authController.registerHandler
        );

        // Login route
        this.router.post('/login', 
            authValidator.loginValidation,
            authController.loginHandler
        );
    }

    getRouter() {
        return this.router;
    }
}

module.exports = new AuthRoutes().getRouter();

// Generated by Copilot
