const express = require('express');
const projectController = require('./project.controller');
const projectValidator = require('./project.validator');
const authMiddleware = require('../auth/auth.middleware');

class ProjectRoutes {
    constructor() {
        this.router = express.Router();
        this.initializeRoutes();
    }

    initializeRoutes() {
        // List projects in workspace (must come before /:projectId)
        this.router.get('/workspace/:workspaceId',
            authMiddleware.authenticateToken,
            projectController.listWorkspaceProjectsHandler
        );

        // Create project
        this.router.post('/',
            authMiddleware.authenticateToken,
            projectValidator.createProjectValidation,
            projectController.createProjectHandler
        );

        // Get project details
        this.router.get('/:projectId',
            authMiddleware.authenticateToken,
            projectValidator.projectIdValidation,
            projectController.getProjectDetailsHandler
        );

        // Update project
        this.router.put('/:projectId',
            authMiddleware.authenticateToken,
            projectValidator.updateProjectValidation,
            projectController.updateProjectHandler
        );

        // Delete project
        this.router.delete('/:projectId',
            authMiddleware.authenticateToken,
            projectValidator.projectIdValidation,
            projectController.deleteProjectHandler
        );

        // Add project member
        this.router.post('/:projectId/members',
            authMiddleware.authenticateToken,
            projectValidator.addMemberValidation,
            projectController.addProjectMemberHandler
        );

        // Remove project member
        this.router.delete('/:projectId/members/:userId',
            authMiddleware.authenticateToken,
            projectValidator.removeMemberValidation,
            projectController.removeProjectMemberHandler
        );
    }

    getRouter() {
        return this.router;
    }
}

module.exports = new ProjectRoutes().getRouter();

// Generated by Copilot
